services:
  - type: web
    name: backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py 
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: mysql+pymysql://root:Cool%40676@localhost/tele_trade_data_db